import Foundation
import os.log

private let logger = Logger(subsystem: "com.shadow.app", category: "LoRATrainer")

/// Orchestrates LoRA fine-tuning of the grounding model (ShowUI-2B) using
/// training data generated by `TrainingDataGenerator`.
///
/// LoRA (Low-Rank Adaptation) adapts the pretrained ShowUI-2B model to the user's
/// specific desktop environment -- their apps, their themes, their layouts -- without
/// modifying the original weights. The adapter weights are small (~20-50 MB) and
/// merge at inference time.
///
/// Training is done via the `mlx-vlm` Python package (VLM-specific MLX LoRA trainer).
/// ShowUI-2B is a vision-language model, so we use `mlx_vlm.lora` (not `mlx_lm.lora`).
/// This actor orchestrates the Python subprocess, monitors progress, and installs
/// the resulting adapter weights for use by `LocalGroundingModel`.
///
/// Training schedule:
/// - **Trigger**: When `TrainingDataGenerator` has accumulated >= 100 new tuples
///   since the last training run.
/// - **Frequency**: At most once per 24 hours to avoid GPU contention.
/// - **Priority**: Background quality-of-service. Yields to inference workloads.
///
/// Mimicry Phase B: LoRA Fine-Tuning Orchestrator.
actor LoRATrainer {

    /// Configuration for a training run.
    struct TrainingConfig: Sendable {
        /// Minimum number of training tuples before triggering a run.
        let minTuples: Int
        /// LoRA rank (dimensionality of the adapter). Lower = smaller adapter.
        let loraRank: Int
        /// Number of training iterations.
        let iterations: Int
        /// Learning rate.
        let learningRate: Double
        /// Batch size.
        let batchSize: Int
        /// Minimum hours between training runs.
        let minHoursBetweenRuns: Double

        static let `default` = TrainingConfig(
            minTuples: 100,
            loraRank: 8,
            iterations: 200,
            learningRate: 1e-4,
            batchSize: 4,
            minHoursBetweenRuns: 24
        )
    }

    /// Status of the trainer.
    enum TrainerStatus: String, Sendable {
        case idle
        case preparing
        case training
        case merging
        case failed
        case completed
    }

    // MARK: - State

    /// Base directory for training data and model adapters.
    private let dataDir: URL

    /// Directory where adapter weights are stored.
    private let adaptersDir: URL

    /// Current status.
    private(set) var status: TrainerStatus = .idle

    /// Last training run completion time.
    private(set) var lastRunTime: Date?

    /// Number of successful training runs this session.
    private(set) var runsCompleted: Int = 0

    /// Number of failed training runs this session.
    private(set) var runsFailed: Int = 0

    /// The training data generator to query for tuple counts.
    private let dataGenerator: TrainingDataGenerator

    /// Training configuration.
    private let config: TrainingConfig

    /// Currently running training process (if any).
    private var trainingProcess: Process?

    // MARK: - Init

    init(
        dataGenerator: TrainingDataGenerator,
        config: TrainingConfig = .default,
        dataDir: URL? = nil
    ) {
        let base = dataDir ?? FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".shadow/data/training")
        self.dataDir = base
        self.adaptersDir = base.appendingPathComponent("adapters")
        self.dataGenerator = dataGenerator
        self.config = config
    }

    // MARK: - Training Trigger

    /// Check if training should be triggered and run if so.
    ///
    /// Conditions for triggering:
    /// 1. Enough training tuples (>= minTuples)
    /// 2. Enough time since last run (>= minHoursBetweenRuns)
    /// 3. Not currently training
    /// 4. mlx-lm Python package is available
    ///
    /// - Returns: True if training was triggered and completed successfully.
    @discardableResult
    func checkAndTrain() async -> Bool {
        guard status == .idle else {
            logger.debug("Training skipped: status=\(self.status.rawValue)")
            return false
        }

        // Check time since last run
        if let lastRun = lastRunTime {
            let hoursSince = Date().timeIntervalSince(lastRun) / 3600
            if hoursSince < config.minHoursBetweenRuns {
                logger.debug("Training skipped: only \(String(format: "%.1f", hoursSince))h since last run (need \(self.config.minHoursBetweenRuns)h)")
                return false
            }
        }

        // Check tuple count
        let tupleCount = await dataGenerator.totalTupleCount()
        guard tupleCount >= config.minTuples else {
            logger.debug("Training skipped: \(tupleCount) tuples (need \(self.config.minTuples))")
            return false
        }

        // Check mlx-vlm availability (ShowUI-2B is a VLM, requires mlx-vlm not mlx-lm)
        guard isMLXVLMAvailable() else {
            logger.warning("Training skipped: mlx-vlm Python package not found. Install with: pip install mlx-vlm")
            return false
        }

        return await runTraining()
    }

    // MARK: - Training Execution

    /// Execute a LoRA fine-tuning run.
    ///
    /// Runs `mlx_lm.lora` via Python subprocess with the training data JSONL files
    /// and the base ShowUI-2B model. Produces adapter weights in the adapters directory.
    private func runTraining() async -> Bool {
        status = .preparing
        DiagnosticsStore.shared.increment("lora_training_attempt_total")
        let startTime = CFAbsoluteTimeGetCurrent()

        do {
            try ensureDirectories()
        } catch {
            logger.error("Failed to create adapter directories: \(error, privacy: .public)")
            status = .failed
            runsFailed += 1
            return false
        }

        // Find all training JSONL files
        let groundingDir = dataDir.appendingPathComponent("grounding")
        guard let files = try? FileManager.default.contentsOfDirectory(
            at: groundingDir,
            includingPropertiesForKeys: nil
        ) else {
            logger.error("Failed to list training data files")
            status = .failed
            runsFailed += 1
            return false
        }

        let jsonlFiles = files.filter { $0.pathExtension == "jsonl" }
        guard !jsonlFiles.isEmpty else {
            logger.warning("No JSONL training files found")
            status = .idle
            return false
        }

        // Merge all JSONL files into a single training file
        let mergedFile = dataDir.appendingPathComponent("train.jsonl")
        do {
            var allLines: [String] = []
            for file in jsonlFiles {
                let content = try String(contentsOf: file, encoding: .utf8)
                let lines = content.components(separatedBy: "\n").filter { !$0.isEmpty }
                allLines.append(contentsOf: lines)
            }
            let merged = allLines.joined(separator: "\n") + "\n"
            try merged.write(to: mergedFile, atomically: true, encoding: .utf8)
            logger.info("Merged \(allLines.count) training tuples into train.jsonl")
        } catch {
            logger.error("Failed to merge training files: \(error, privacy: .public)")
            status = .failed
            runsFailed += 1
            return false
        }

        // Resolve the base model path
        let modelPath = LocalModelRegistry.modelPath(for: LocalModelRegistry.groundingDefault)
        guard FileManager.default.fileExists(atPath: modelPath.path) else {
            logger.error("Base grounding model not found at \(modelPath.path)")
            status = .failed
            runsFailed += 1
            return false
        }

        // Run mlx_lm.lora training via Python
        status = .training
        let adapterOutputDir = adaptersDir.appendingPathComponent(
            "adapter-\(dateString())"
        )

        let success = await runMLXLMTraining(
            modelPath: modelPath.path,
            dataPath: mergedFile.path,
            outputPath: adapterOutputDir.path,
            config: config
        )

        if success {
            status = .completed
            lastRunTime = Date()
            runsCompleted += 1
            let elapsed = (CFAbsoluteTimeGetCurrent() - startTime) / 60
            DiagnosticsStore.shared.increment("lora_training_success_total")
            DiagnosticsStore.shared.recordLatency(
                "lora_training_duration_minutes",
                ms: elapsed * 60_000
            )
            logger.info("LoRA training completed in \(String(format: "%.1f", elapsed)) minutes")

            // Install the adapter for use by LocalGroundingModel
            installAdapter(from: adapterOutputDir)
        } else {
            status = .failed
            runsFailed += 1
            DiagnosticsStore.shared.increment("lora_training_fail_total")
            logger.error("LoRA training failed")
        }

        // Reset to idle after a brief delay
        status = .idle
        return success
    }

    /// Execute the mlx_vlm LoRA training command.
    ///
    /// ShowUI-2B is a VLM so we use `mlx_vlm.lora` (not `mlx_lm.lora`).
    /// The actual CLI arguments for mlx-vlm's lora.py are:
    ///   --model-path, --dataset, --output-path, --learning-rate, --batch-size, --epochs
    ///
    /// Note: `--dataset` expects a directory containing a HuggingFace-compatible dataset
    /// with `images` and `messages` columns, or a local directory the script can load.
    /// The TrainingDataGenerator writes JSONL files that serve as the data source;
    /// we pass the parent directory containing these files.
    private func runMLXLMTraining(
        modelPath: String,
        dataPath: String,
        outputPath: String,
        config: TrainingConfig
    ) async -> Bool {
        // Build the mlx_vlm.lora command
        // mlx_vlm.lora --model-path <path> --dataset <dir> --output-path <output>
        //   --learning-rate <lr> --batch-size <bs> --epochs <n>
        //
        // Note: mlx_vlm.lora does not support --lora-rank or --iters flags.
        // Epochs are used instead of iterations; the script handles iteration
        // counting internally based on dataset size.
        let epochs = max(1, config.iterations / 50) // approximate: 50 steps per epoch
        let args = [
            "-m", "mlx_vlm.lora",
            "--model-path", modelPath,
            "--dataset", dataPath,
            "--output-path", outputPath,
            "--learning-rate", String(config.learningRate),
            "--batch-size", String(config.batchSize),
            "--epochs", String(epochs)
        ]

        return await withCheckedContinuation { continuation in
            let process = Process()
            process.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
            process.arguments = args
            process.environment = ProcessInfo.processInfo.environment
            process.qualityOfService = .background

            // Capture stdout and stderr for logging
            let pipe = Pipe()
            process.standardOutput = pipe
            process.standardError = pipe

            do {
                try process.run()
                self.trainingProcess = process
            } catch {
                logger.error("Failed to launch mlx_vlm.lora: \(error, privacy: .public)")
                continuation.resume(returning: false)
                return
            }

            // Wait for completion in background
            process.terminationHandler = { [weak self] proc in
                let data = pipe.fileHandleForReading.readDataToEndOfFile()
                let output = String(data: data, encoding: .utf8) ?? ""

                if proc.terminationStatus == 0 {
                    logger.info("mlx_vlm.lora completed successfully")
                    if !output.isEmpty {
                        logger.debug("Training output: \(output.suffix(500), privacy: .public)")
                    }
                } else {
                    logger.error("mlx_vlm.lora failed with status \(proc.terminationStatus): \(output.suffix(500), privacy: .public)")
                }

                Task { [weak self] in
                    await self?.clearTrainingProcess()
                }
                continuation.resume(returning: proc.terminationStatus == 0)
            }
        }
    }

    /// Clear the training process reference.
    private func clearTrainingProcess() {
        trainingProcess = nil
    }

    /// Cancel any in-progress training.
    func cancelTraining() {
        guard let process = trainingProcess, process.isRunning else { return }
        process.terminate()
        trainingProcess = nil
        status = .idle
        logger.info("Training cancelled by user")
    }

    // MARK: - Adapter Management

    /// Install a completed adapter by symlinking it to the active adapter path.
    ///
    /// The `LocalGroundingModel` looks for adapters at a well-known path.
    /// After training completes, we symlink the latest adapter there.
    private func installAdapter(from adapterDir: URL) {
        let activeLink = adaptersDir.appendingPathComponent("active")
        let fm = FileManager.default

        // Remove old symlink
        try? fm.removeItem(at: activeLink)

        // Create new symlink
        do {
            try fm.createSymbolicLink(
                at: activeLink,
                withDestinationURL: adapterDir
            )
            logger.info("Installed adapter: \(adapterDir.lastPathComponent) -> active")
        } catch {
            logger.error("Failed to install adapter: \(error, privacy: .public)")
        }
    }

    /// Path to the currently active adapter, if any.
    var activeAdapterPath: URL? {
        let active = adaptersDir.appendingPathComponent("active")
        guard FileManager.default.fileExists(atPath: active.path) else { return nil }
        return active
    }

    /// List all available adapters.
    func listAdapters() -> [URL] {
        guard let contents = try? FileManager.default.contentsOfDirectory(
            at: adaptersDir,
            includingPropertiesForKeys: [.isDirectoryKey]
        ) else { return [] }

        return contents.filter { url in
            var isDir: ObjCBool = false
            FileManager.default.fileExists(atPath: url.path, isDirectory: &isDir)
            return isDir.boolValue && url.lastPathComponent != "active"
        }
    }

    // MARK: - Availability

    /// Check if mlx-vlm Python package is installed.
    /// ShowUI-2B is a vision-language model, so we need mlx-vlm (not mlx-lm).
    private func isMLXVLMAvailable() -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
        process.arguments = ["-c", "import mlx_vlm; print('ok')"]
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice

        do {
            try process.run()
            process.waitUntilExit()
            return process.terminationStatus == 0
        } catch {
            return false
        }
    }

    // MARK: - Helpers

    private func ensureDirectories() throws {
        try FileManager.default.createDirectory(
            at: adaptersDir,
            withIntermediateDirectories: true
        )
    }

    private func dateString() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd-HHmmss"
        return formatter.string(from: Date())
    }
}
