import Foundation

// MARK: - Suggestion Types

/// Categories of proactive suggestions.
enum SuggestionType: String, Codable, Sendable, CaseIterable {
    case meetingPrep = "meeting_prep"
    case followup = "followup"
    case workloadPattern = "workload_pattern"
    case reminder = "reminder"
    case contextSwitch = "context_switch"
    case dailyDigest = "daily_digest"
}

/// Policy decision for a proactive suggestion.
enum SuggestionDecision: String, Codable, Sendable {
    case pushNow = "push_now"
    case inboxOnly = "inbox_only"
    case drop = "drop"
}

/// Lifecycle status of a suggestion.
enum SuggestionStatus: String, Codable, Sendable {
    case active
    case dismissed
    case snoozed
    case acted
    case archived
}

/// Feedback event types for explicit user signals.
enum FeedbackEventType: String, Codable, Sendable {
    case thumbsUp = "thumbs_up"
    case thumbsDown = "thumbs_down"
    case dismiss
    case snooze
}

/// Confidence band for human-readable display.
enum ConfidenceBand: String, Codable, Sendable {
    case high
    case medium
    case low

    init(score: Double) {
        if score >= 0.82 { self = .high }
        else if score >= 0.55 { self = .medium }
        else { self = .low }
    }
}

// MARK: - Proactive Suggestion

/// A proactive suggestion generated by the analyzer.
struct ProactiveSuggestion: Codable, Identifiable, Sendable, Equatable {
    let id: UUID
    let createdAt: Date
    let type: SuggestionType
    let title: String
    let body: String
    let whyNow: String
    let confidence: Double
    let decision: SuggestionDecision
    let evidence: [SuggestionEvidence]
    let sourceRecordIds: [String]
    var status: SuggestionStatus

    var confidenceBand: ConfidenceBand {
        ConfidenceBand(score: confidence)
    }
}

/// Evidence anchor for a suggestion, referencing timeline data.
struct SuggestionEvidence: Codable, Sendable, Equatable {
    let timestamp: UInt64
    let app: String?
    let sourceKind: String
    let displayId: UInt32?
    let url: String?
    let snippet: String
}

// MARK: - Proactive Feedback

/// Explicit feedback event from the user on a suggestion.
struct ProactiveFeedback: Codable, Identifiable, Sendable, Equatable {
    let id: UUID
    let suggestionId: UUID
    let eventType: FeedbackEventType
    let timestamp: Date
    let foregroundApp: String?
    let displayId: UInt32?
}

// MARK: - Proactive Run Record

/// Status of a proactive engine run.
enum ProactiveRunStatus: String, Codable, Sendable {
    case running
    case completed
    case failed
    case skipped
}

/// Record of a single proactive engine run, for observability.
struct ProactiveRunRecord: Codable, Identifiable, Sendable, Equatable {
    let id: UUID
    let startedAt: Date
    var endedAt: Date?
    var status: ProactiveRunStatus
    var model: String?
    var latencyMs: Double?
    var decision: SuggestionDecision?
    var confidence: Double?
    var whyNow: String?
    var evidenceRefs: [SuggestionEvidence]
    var errorSummary: String?
    var sourceRecordIds: [String]

    /// Create a new run record at the start of a run.
    static func start() -> ProactiveRunRecord {
        ProactiveRunRecord(
            id: UUID(),
            startedAt: Date(),
            endedAt: nil,
            status: .running,
            model: nil,
            latencyMs: nil,
            decision: nil,
            confidence: nil,
            whyNow: nil,
            evidenceRefs: [],
            errorSummary: nil,
            sourceRecordIds: []
        )
    }

    /// Mark the run as completed with results.
    mutating func complete(
        decision: SuggestionDecision,
        confidence: Double,
        whyNow: String?,
        model: String?,
        evidenceRefs: [SuggestionEvidence] = [],
        sourceRecordIds: [String] = []
    ) {
        self.endedAt = Date()
        self.status = .completed
        self.decision = decision
        self.confidence = confidence
        self.whyNow = whyNow
        self.model = model
        self.latencyMs = endedAt.map { $0.timeIntervalSince(startedAt) * 1000 }
        self.evidenceRefs = evidenceRefs
        self.sourceRecordIds = sourceRecordIds
    }

    /// Mark the run as failed.
    mutating func fail(error: String) {
        self.endedAt = Date()
        self.status = .failed
        self.latencyMs = endedAt.map { $0.timeIntervalSince(startedAt) * 1000 }
        self.errorSummary = error
    }

    /// Mark the run as skipped (change delta too low, cooldown, etc.).
    mutating func skip(reason: String) {
        self.endedAt = Date()
        self.status = .skipped
        self.latencyMs = 0
        self.errorSummary = reason
    }
}

// MARK: - Engine Status

/// Current operational status of the proactive engine.
enum ProactiveEngineStatus: String, Codable, Sendable {
    case idle
    case running
    case backoff
    case error
}

// MARK: - Policy Input

/// Input features for the policy engine scoring function.
struct PolicyInput: Sendable {
    let suggestionType: SuggestionType
    let confidence: Double
    let evidenceQuality: Double
    let noveltyScore: Double
    let interruptionCost: Double
    let preferenceAffinity: Double
}

/// Output of the policy engine.
struct PolicyOutput: Sendable, Equatable {
    let decision: SuggestionDecision
    let score: Double
    let rationale: String
}
